name: Assign Pull Request Creator

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'
      - 'stable'
      - 'release/v*'

permissions:
  contents: read

jobs:
  assign-assignees:
    permissions:
      issues: write
      pull-requests: write
    uses: dafneb/.github/.github/workflows/pull-request-assignee.yml@3c0ec941b8e9e7692e5a8105bd64a488cf164612
    with:
      assignees: ${{ github.actor }}
