name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '35 23 * * 5'
  push:
    branches:
      - 'main'
      - 'stable'
    paths-ignore:
      - '.github/workflows/*'

permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: dafneb/.github/.github/workflows/scorecard.yml@3c0ec941b8e9e7692e5a8105bd64a488cf164612
    secrets:
      SCORECARD_TOKEN: ${{ secrets.SCORECARD_TOKEN }}
